# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :screenshots do
      clear_derived_data()
      
      configuration = "ScreenshotTest"
      devices = ["iPad Pro (12.9-inch) (3rd generation)", "iPhone Xs Max"]
      languages = ["de-DE"]
      
      capture_screenshots(configuration: configuration,
                          languages: [languages],
                          devices: devices,
                          clean: true,
                          clear_previous_screenshots: true,
                          erase_simulator: true)
  end
end
